# 사이트 기본 정보
title: DBL-Diffusion
description: DBL-Diffusion: Explicit Layer Modeling for Video Object Insertion and Video Layer Decomposition
author: Kyujin Han

# URL 설정 (username.github.io 또는 사용자 페이지 주소)
url: "https://kyujinhan.github.io"
baseurl: "/dual-branch-layered-diffusion" # 프로젝트 페이지인 경우 "/<리포지토리이름>" 형태로 입력

# 사용할 Jekyll 테마 (기본 테마 또는 외부 테마명)
theme: minima

# 빌드 시 제외할 파일/폴더
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
